on:
  push:
    paths:
       - fantasy.Rmd
       
name: Render fantasy page

jobs:
  render:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-tinytex@v1
      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown")'
      - name: Render document
        run: Rscript -e 'rmarkdown::render("fantasy.Rmd", output_format = "md_document")'
      - name: Commit results
        run: |
          git add fantasy.md
          git commit -m "Push new fantasy page" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
