name: Make stat table

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v1
    - uses: r-lib/actions/setup-pandoc@v1
    
    - name: Install and activate renv
      run: |
        install.packages("renv")
        renv::activate()
      shell: Rscript {0}
    
    - uses: actions/cache@v2
      with:
         path: ~/.local/share/renv
         key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
         restore-keys: ${{ runner.os }}-renv-
        
    - name: Run script
      run: Rscript -e 'source("tables/tableworkflow.R")'

    - name: Commit results
      run: |
        git config --local user.name "$GITHUB_ACTOR"
        git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git add .
        git commit -m 'Update latest table' || echo "No changes to commit"
        git push origin || echo "No changes to commit"
