name: Make stat table

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v1
    - uses: r-lib/actions/setup-pandoc@v1
    
    - uses: actions/cache@v2
      with:
         path: ~/.local/share/renv
         key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
         restore-keys: ${{ runner.os }}-renv-
    
    - name: Install packages
      run: |
        R -e 'install.packages("renv")'
        R -e 'renv::restore()'
        R -e 'install.packages("rmarkdown")'
        R -e 'install.packages("tidyverse")'
        R -e 'install.packages("glue")'
        R -e 'install.packages("lubridate")'
        R -e 'install.packages("DBI")'
        R -e 'install.packages("RSQLite")'
        R -e 'install.packages("gsisdecoder")'
        R -e 'install.packages("devtools")'
        R -e 'install.packages("nflfastR")'
        R -e 'devtools::install_github("Puntalytics/puntr")'
        R -e 'install.packages("gt")'
        R -e 'remotes::install_github("jthomasmock/gtExtras")'
       
    - name: Run script
      run: R -e 'source("tables/tableworkflow.R")'

    - name: Commit results
      run: |
        git config --local user.name "$GITHUB_ACTOR"
        git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git add tables/latest.html
        git commit -m 'Update latest table' || echo "No changes to commit"
        git push origin || echo "No changes to commit"
